[package]
name = "kalz_websocket_server"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1.28.0", features = ["full"] }
futures-util = "0.3"
tokio-tungstenite = "0.18.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
